# Generated by Django 6.1 on 2026-09-01 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_orders', models.IntegerField()),
                ('total_payments', models.IntegerField()),
                ('total_order_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value_reconciled', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value_in_dispute', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discrepancy_count', models.IntegerField()),
                ('by_type_json', models.JSONField(default=dict)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_run', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MISSING_PAYMENT', 'MISSING_PAYMENT'), ('ORPHAN_PAYMENT', 'ORPHAN_PAYMENT'), ('DUPLICATE_CHARGE', 'DUPLICATE_CHARGE'), ('CURRENCY_MISMATCH', 'CURRENCY_MISMATCH'), ('AMOUNT_UNDERPAID', 'AMOUNT_UNDERPAID'), ('AMOUNT_OVERPAID', 'AMOUNT_OVERPAID'), ('UNSETTLED_PAYMENT', 'UNSETTLED_PAYMENT'), ('CANCELLED_NOT_REFUNDED', 'CANCELLED_NOT_REFUNDED'), ('REFUND_STATUS_DRIFT', 'REFUND_STATUS_DRIFT')], db_index=True, max_length=32)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payment_refs_json', models.JSONField(default=list)),
                ('amount_at_risk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detail', models.TextField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='reconciliation.reconciliationrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'type'], name='reconciliat_run_id_6f3fa9_idx')],
            },
        ),
    ]
