# Generated by Django 6.1 on 2026-09-01 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=64)),
                ('processed_at_raw', models.CharField(blank=True, max_length=64, null=True)),
                ('order_reference', models.CharField(max_length=64)),
                ('order_reference_normalized', models.CharField(db_index=True, max_length=64)),
                ('currency', models.CharField(max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_settled', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'order_reference_normalized'], name='payments_pa_owner_i_b4aecf_idx')],
            },
        ),
    ]
